delete from `rv_email_template` where name = 'yearly_assessment_staff_commit';
delete from `rv_email_template` where name = 'yearly_assessment_to_director_commit';
delete from `rv_email_template` where name = 'yearly_assessment_to_consturct_commit';
delete from `rv_email_template` where name = 'yearly_assessment_to_ceo_commit';
delete from `rv_email_template` where name = 'yearly_assessment_to_system_admin';
delete from `rv_email_template` where name = 'yearly_assessment_to_reject_to_staff';
delete from `rv_email_template` where name = 'yearly_assessment_to_reject_to_director';
delete from `rv_email_template` where name = 'yearly_assessment_to_delay';
delete from `rv_email_template` where name = 'monthly_assessment_finish';

INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('monthly_assessment_finish', '【考評核准通知】{year}年{month}月 績效評核表', '<h3>您好：</h3><p>此月份考評單已經全部核准 </p> <p>特此通知</p>', 0, '2017-08-04 17:43:15');

INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_staff_commit', '【送達通知】{year}年 {divison_name} {staff_name_en} {staff_name} 年度考核表已提交', '<h3>您好：</h3><p> {year} 年度 {divison_name} {staff_name_en} {staff_name} 送審之年度考核表已抵達您的手中，請儘速完成評核作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_director_commit', '【送達通知】【{divison_name}】{year}年 年度考核表已全數收齊', '<h3>您好：</h3><p> {year} 年度 {divison_name} 送審之年度考核表已全數抵達您的手中，請儘速完成評核作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_consturct_commit', '【送達通知】【{divison_name}】{year}年 年度考核表 等待確認', '<h3>您好：</h3><p> {year} 年度 {divison_name}  送審之年度考核表已抵達您的手中，請儘速完成確認作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_ceo_commit', '【待批准通知】【{divison_name}】{year}年 年度考核表 ', '<h3>您好：</h3><p> {year} 年度 {divison_name}  送審之年度考核表已抵達您的手中，請儘速完成核準作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_system_admin', '【批准通知】{year}年 年度考核已全數批准 ', '<h3>您好：</h3><p> {year} 年度之年度考核已全數完成，請儘速完成作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_reject_to_staff', '【駁回通知】{year} 年 {divison_name} {staff_name_en} {staff_name} 的年度考核表已駁回', '<h3>您好：</h3><p> {year} 年度 {divison_name} {staff_name_en} {staff_name} 送審之年度考核表已駁回，請儘速完成評核作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_reject_to_director', '【駁回通知】【{divison_name}】{year}年的年度考核表已駁回', '<h3>您好：</h3><p> {year} 年度 {divison_name} 送審之年度考核表已駁回，請儘速完成評核作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');
INSERT INTO `rv_email_template` (`name`, `title`, `text`, `update_operatinger_id`, `update_date`) VALUES ('yearly_assessment_to_delay', '【考評通知】 {year} {divison_name} {staff_name_en} {staff_name}', '<h3>您好：</h3><p> {year} 年度考核作業已過截止時間 ( {yearly_assessment_dead_line} ) ，請儘速完成評核作業，謝謝！<p> 入口網址: <a target="_blank" href="{site_host}">{site_host}</a> </p> <p> 帳     號：員編 </p> <p>密     碼：身分證字號（預設） </p> <br><br> <p>人力資源處</p>', 0, '2017-08-15 17:43:15');